package capstone;

import static capstone.CharacterClass.valueOf;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Marvin
 */
public class Gui extends javax.swing.JPanel {
    
    Attributes attributes;
    int activeField = 1;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vigorTextField = new javax.swing.JTextField(2);
        mindTextField = new javax.swing.JTextField(2);
        enduranceTextField = new javax.swing.JTextField(2);
        strengthTextField = new javax.swing.JTextField(2);
        dexterityTextField = new javax.swing.JTextField(2);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        intelligenceTextField = new javax.swing.JTextField(2);
        jLabel6 = new javax.swing.JLabel();
        faithTextField = new javax.swing.JTextField(2);
        arcaneTextField = new javax.swing.JTextField(2);
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nextLevelTextField = new javax.swing.JTextField(8);
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalRunesTextField = new javax.swing.JTextField(8);
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        ((JLabel)jComboBox1.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        increaseButton = new javax.swing.JButton();
        decreaseButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        levelTextField = new javax.swing.JTextField();

        vigorTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vigorTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vigorTextField.setText("0");
        vigorTextField.setToolTipText("");
        vigorTextField.setMaximumSize(new java.awt.Dimension(71, 22));
        vigorTextField.setMinimumSize(new java.awt.Dimension(71, 22));
        vigorTextField.setName("vigorTextField"); // NOI18N
        vigorTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                vigorTextFieldCaretUpdate(evt);
            }
        });

        mindTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mindTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mindTextField.setText("0");
        mindTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                mindTextFieldCaretUpdate(evt);
            }
        });

        enduranceTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        enduranceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enduranceTextField.setText("0");
        enduranceTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                enduranceTextFieldCaretUpdate(evt);
            }
        });

        strengthTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        strengthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        strengthTextField.setText("0");
        strengthTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                strengthTextFieldCaretUpdate(evt);
            }
        });

        dexterityTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dexterityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dexterityTextField.setText("0");
        dexterityTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                dexterityTextFieldCaretUpdate(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Vigor");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Mind");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Endurance");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Strength");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Dexterity");

        intelligenceTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intelligenceTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        intelligenceTextField.setText("0");
        intelligenceTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                intelligenceTextFieldCaretUpdate(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Intelligence");

        faithTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        faithTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        faithTextField.setText("0");
        faithTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                faithTextFieldCaretUpdate(evt);
            }
        });

        arcaneTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arcaneTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arcaneTextField.setText("0");
        arcaneTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                arcaneTextFieldCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Faith");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Arcane");

        nextLevelTextField.setEditable(false);
        nextLevelTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextLevelTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        nextLevelTextField.setText("50000");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Next Level");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Total Runes");

        totalRunesTextField.setEditable(false);
        totalRunesTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalRunesTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        totalRunesTextField.setText("2452452450");

        jLabel11.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel11.setText("RUNE CALCULATOR");

        jComboBox1.setModel(new DefaultComboBoxModel<>(CharacterClass.values())
        );
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        increaseButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        increaseButton.setForeground(new java.awt.Color(0, 153, 0));
        increaseButton.setText("INCREASE");
        increaseButton.setToolTipText("");
        increaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                increaseButtonMouseReleased(evt);
            }
        });

        decreaseButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        decreaseButton.setForeground(new java.awt.Color(255, 0, 51));
        decreaseButton.setText("DECREASE");
        decreaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                decreaseButtonMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel12.setText("LEVEL");

        levelTextField.setEditable(false);
        levelTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        levelTextField.setForeground(new java.awt.Color(204, 0, 51));
        levelTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        levelTextField.setText("999");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalRunesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextLevelTextField)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(increaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arcaneTextField)
                    .addComponent(faithTextField)
                    .addComponent(intelligenceTextField)
                    .addComponent(dexterityTextField)
                    .addComponent(strengthTextField)
                    .addComponent(vigorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mindTextField)
                    .addComponent(enduranceTextField))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(levelTextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vigorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mindTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enduranceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(strengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(increaseButton)
                                .addGap(18, 18, 18)
                                .addComponent(decreaseButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dexterityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intelligenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faithTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arcaneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextLevelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalRunesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(levelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        CharacterClass choice = (valueOf(jComboBox1.getSelectedItem().toString()));
        attributes = new Attributes(choice);
        vigorTextField.setText(attributes.getVigor());
        mindTextField.setText(attributes.getMind());
        enduranceTextField.setText(attributes.getEndurance());
        strengthTextField.setText(attributes.getStrength());
        dexterityTextField.setText(attributes.getDexterity());
        intelligenceTextField.setText(attributes.getIntelligence());
        faithTextField.setText(attributes.getFaith());
        arcaneTextField.setText(attributes.getArcane());
        levelTextField.setText(attributes.getLevel());
        totalRunesTextField.setText(attributes.getTotalRunes());
        activeField = 1;
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void vigorTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_vigorTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 1;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_vigorTextFieldCaretUpdate

    private void mindTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_mindTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 2;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_mindTextFieldCaretUpdate

    private void enduranceTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_enduranceTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 3;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_enduranceTextFieldCaretUpdate

    private void strengthTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_strengthTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 4;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_strengthTextFieldCaretUpdate

    private void dexterityTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_dexterityTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 5;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_dexterityTextFieldCaretUpdate

    private void intelligenceTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_intelligenceTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 6;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_intelligenceTextFieldCaretUpdate

    private void faithTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_faithTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 7;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_faithTextFieldCaretUpdate

    private void arcaneTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_arcaneTextFieldCaretUpdate
        // TODO add your handling code here:
        activeField = 8;
        System.out.println("Active Field: = " + activeField);
    }//GEN-LAST:event_arcaneTextFieldCaretUpdate

    private void increaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_increaseButtonMouseReleased
        // TODO add your handling code here:
        String str;
        int value;
        switch (activeField) {
            case 1:
                str = vigorTextField.getText();
                value = convertAndIncrement(str);
                System.out.println(value);
                attributes.setVigor(value);
                vigorTextField.setText(attributes.getVigor());
                break;
            case 2:
                str = mindTextField.getText();
                value = convertAndIncrement(str);
                attributes.setMind(value);
                System.out.println(value);
                mindTextField.setText(attributes.getMind());
                break;
            case 3:
                str = enduranceTextField.getText();
                value = convertAndIncrement(str);
                attributes.setEndurance(value);
                System.out.println(value);
                enduranceTextField.setText(attributes.getEndurance());
                break;
            case 4:
                str = strengthTextField.getText();
                value = convertAndIncrement(str);
                attributes.setStrength(value);
                System.out.println(value);
                strengthTextField.setText(attributes.getStrength());
                break;
            case 5:
                str = dexterityTextField.getText();
                value = convertAndIncrement(str);
                attributes.setDexterity(value);
                System.out.println(value);
                dexterityTextField.setText(attributes.getDexterity());
                break;
            case 6:
                str = intelligenceTextField.getText();
                value = convertAndIncrement(str);
                attributes.setIntelligence(value);
                System.out.println(value);
                intelligenceTextField.setText(attributes.getIntelligence());
                break;
            case 7:
                str = faithTextField.getText();
                value = convertAndIncrement(str);
                attributes.setFaith(value);
                System.out.println(value);
                faithTextField.setText(attributes.getFaith());
                break;
            case 8:
                str = arcaneTextField.getText();
                value = convertAndIncrement(str);
                attributes.setArcane(value);
                System.out.println(value);
                arcaneTextField.setText(attributes.getArcane());
                break;

        }
        String levelText = attributes.getLevel();
        int level = convertAndIncrement(levelText);
        attributes.setLevel(level);
        levelTextField.setText(attributes.getLevel());
        nextLevelTextField.setText(attributes.getNextLevel());
        totalRunesTextField.setText(attributes.getTotalRunes());
    }//GEN-LAST:event_increaseButtonMouseReleased

    private void decreaseButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decreaseButtonMouseReleased
        // TODO add your handling code here:
        String str;
        int value;
        switch (activeField) {
            case 1:
                str = vigorTextField.getText();
                value = convertAndDecrement(str);
                System.out.println(value);
                attributes.setVigor(value);
                vigorTextField.setText(attributes.getVigor());
                break;
            case 2:
                str = mindTextField.getText();
                value = convertAndDecrement(str);
                attributes.setMind(value);
                System.out.println(value);
                mindTextField.setText(attributes.getMind());
                break;
            case 3:
                str = enduranceTextField.getText();
                value = convertAndDecrement(str);
                attributes.setEndurance(value);
                System.out.println(value);
                enduranceTextField.setText(attributes.getEndurance());
                break;
            case 4:
                str = strengthTextField.getText();
                value = convertAndDecrement(str);
                attributes.setStrength(value);
                System.out.println(value);
                strengthTextField.setText(attributes.getStrength());
                break;
            case 5:
                str = dexterityTextField.getText();
                value = convertAndDecrement(str);
                attributes.setDexterity(value);
                System.out.println(value);
                dexterityTextField.setText(attributes.getDexterity());
                break;
            case 6:
                str = intelligenceTextField.getText();
                value = convertAndDecrement(str);
                attributes.setIntelligence(value);
                System.out.println(value);
                intelligenceTextField.setText(attributes.getIntelligence());
                break;
            case 7:
                str = faithTextField.getText();
                value = convertAndDecrement(str);
                attributes.setFaith(value);
                System.out.println(value);
                faithTextField.setText(attributes.getFaith());
                break;
            case 8:
                str = arcaneTextField.getText();
                value = convertAndDecrement(str);
                attributes.setArcane(value);
                System.out.println(value);
                arcaneTextField.setText(attributes.getArcane());
                break;

        }
        String levelText = attributes.getLevel();
        int level = convertAndDecrement(levelText);
        attributes.setLevel(level);
        levelTextField.setText(attributes.getLevel());
        nextLevelTextField.setText(attributes.getNextLevel());
        totalRunesTextField.setText(attributes.getTotalRunes());
    }//GEN-LAST:event_decreaseButtonMouseReleased
    
    
    public int convertAndIncrement(String string) {
        int value = Integer.parseInt(string);
        value++;
        return value;
    }
    
    public int convertAndDecrement(String string) {
        int value = Integer.parseInt(string);
        value--;
        return value;
    }                                            


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arcaneTextField;
    private javax.swing.JButton decreaseButton;
    private javax.swing.JTextField dexterityTextField;
    private javax.swing.JTextField enduranceTextField;
    private javax.swing.JTextField faithTextField;
    private javax.swing.JButton increaseButton;
    private javax.swing.JTextField intelligenceTextField;
    private javax.swing.JComboBox<CharacterClass> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField levelTextField;
    private javax.swing.JTextField mindTextField;
    private javax.swing.JTextField nextLevelTextField;
    private javax.swing.JTextField strengthTextField;
    private javax.swing.JTextField totalRunesTextField;
    private javax.swing.JTextField vigorTextField;
    // End of variables declaration//GEN-END:variables
}
